### ISSUE TITLE
color swatch with name

### ISSUE THREAD

**Issue by myselfgaurav** [tzyganu/Switcher#101]
i want color swatches with name also like for shirt of color : red, green , blue, yellow

i want to show images for each color and color name also , how can i do hit ?? , i there any setting for that in plugin

**Comment by tzyganu** [comment]
@myselfgaurav There is no such setting. but you can change this [code here](https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js#L165) to return the image label also. You can access the label through `$(elem).innerHTML`. Arrange them how ever you want.  
This feature will not be implemented in the extension because since there is a colorswatch module in the core  of 1.9 this becomes obsolete.
So I will close the issue.

**Comment by myselfgaurav** [comment]
yeah but one thing color swatches module of magento does works for simple products also ??

**Comment by tzyganu** [comment]
@myselfgaurav I don't really understand. This module does not work for simple products either. it's for configurable products.
