### ISSUE TITLE
Out of Stock Configurable

### ISSUE THREAD

**Issue by chugginn** [tzyganu/Switcher#112]
When I set a configurable product to out of stock, I like for the options and add to cart to disappear, while the 'Notify me when this is in stock' message appears. But I also like for the simple products in the dropdown to show when out of stock for other products. 

Is this not possible? If I set 'Show out of stock configurations' to Yes, out of stock simple products in the dropdowns will appear as intended. But entire configurable products that are of stock will still show the dropdown options.

If I set 'Show out of stock configurations' to No, the inverse happens where my configurable products are now showing out of stock, but out of stock simple products in dropdowns disappear.

**Comment by tzyganu** [comment]
@chugginn This is right now a limitation of the extension. Actually I think it's a limitation of Magento. I didn't do anything special to show the out of stock configurations. I only set a [flag (provided by Magento) to true](https://github.com/tzyganu/Switcher/blob/master/app/code/community/Easylife/Switcher/Model/Observe[r.php#L58].

I will close this for now because I don't plan to "fix" it, since is't a core "feature".
