### ISSUE TITLE
JS callback didn't completely worked

### ISSUE THREAD

**Issue by MichaelLFR** [tzyganu/Switcher#120]
Bonjour,

Maybe it was related to my Bootstrap + ElevateZoom theme ? Anyway there was an issue : the "more-views" links _then_ the Switcher thumbnails worked to display the good picture with zoom. But when using the more-views links _after_ the Switcher, it was not possible to get the Switcher related picture and zoom anymore.

I just replaced the JS callback in the admin.
Easylife Switcher : 
ProductMediaManager.destroyZoom();
ProductMediaManager.createZoom(jQuery('#image-main'));
My version : 
ProductMediaManager.swapImage($j('#image-main'));

Hope it helps.

**Comment by tzyganu** [comment]
@MichaelLFR Bonjour.
The js callback is there just for this purpose. It allows the developer/user to exectute any js code he/she needs after the image is changed because I cannot make it work for all possible themes and all possible zoomers.  
The default value that comes with the extension works on the default magento theme.  
I will close this for now because this is not actually a bug in the module, it has to do with your custom theme.  
Thank you for this. I'm sure it will help other users that use the same settings you do. 
Cheers.

**Comment by MichaelLFR** [comment]
Wow ! How fast you were ! :D
Yes, it was more a hint than a real issue.

Thank you for your work !
