### ISSUE TITLE
Configurable Showing IN STOCK

### ISSUE THREAD

**Issue by waqasyousuf4u** [tzyganu/Switcher#122]
I set all the Simple Product in Configurable Product to Out of Stock But Still Main Configurable Product Showing IN STOCK Option

http://www.husnacollection.com/store/batwing-silver-grey-78.html

Please Check the Issue

**Comment by tzyganu** [comment]
@waqasyousuf4u This is not really an issue. is more of an inconvenience or a limitation of Magento.  
If you choose not to show the out of stock simple products and the configurable product is out of stock you won't see any configurable attributes. This is how Magento works. 
My only change was to allow the display of out of stock combinations. This makes the add to cart button appear and the configurable attributes, but you won't still be able to add the product to the cart. 
Sorry but I will not fix this mainly because it's not an easy task. It involves changing a lot of default behavior and I try to avoid this.

**Comment by waqasyousuf4u** [comment]
I have no problem with Add to cart Button

I just need that when all the simple products is out of stock so configurable product will also be out of stock

if i disabled the extension it will show out of stock but the drop down size will also be hide

i need to show the sizes also

thanks bro for replying

**Comment by tzyganu** [comment]
@waqasyousuf4u That's what I explained. If a configurable product is out of stock you won't see the dropdown. It's default behavior. What I did was just to simulate that the product is in stock to be able to see the dropdown. You cannot have it both ways without heavy coding.

**Comment by waqasyousuf4u** [comment]
Ohhh

Thanks Bro

**Comment by Christian-Death** [comment]
Hello @tzyganu and @waqasyousuf4u ,

it is not so heavy.
For my own shop i have switcher change for this.

I have Patchfiles for the config.php and for the product.js on GDrive https://drive.google.com/folderview?id=0B6MNreLwW6TefjNaTWo3RUhSWkFWYnBKQkRkWHhoTVVIb19Cb0dTOGpJZmp4MTVqN3hMd2M&usp=sharing

In your /app/design/frontend/rwd/(own_template)/template/catalog/product/view/type/default.phtml

you muss add 
```
<div id="stock_qty">
<p><span><?php echo $this->__('Select an option to see the immediate availability.') ?></span></p>
<?php echo $this->__('ansonsten'); ?>
</div>
```

For better understand my default.phtml is also in the directory.

Sample can you found on http://cherokee-trading.de/holzrahmen-fuer-den-trommelbau-rund.html
Then you change the config, you can see how much is aviable and the delivery time.
