### ISSUE TITLE
Stretches Image

### ISSUE THREAD

**Issue by MrJoshFisher** [tzyganu/Switcher#133]
![screenshot 2015-07-20 16 25 27](https://cloud.githubusercontent.com/assets/8970358/8779583/f74a2ac8-2efb-11e5-8eb7-df94845a304a.png)

Hello All, As you can see from above for some reason its stretching the original image to way over its original size, but when you go into mobile version size its fine, weird one. Also there isn't an option to select the only simple product with an image, I have 50 simple products all using the same colour, now colour is the only option which makes the image switch there isn't a quicker way of saying for all these simple products with the colour black use the black image, is there ?

Great plugin btw makes all the others look crap ha

**Comment by tzyganu** [comment]
@MrJoshFisher You questions are not 100% clear, but I will give it a try.  
The image size can be set in the configuration section. Look for the field `Label / Options image size` [in here](https://github.com/tzyganu/Switcher/wiki/configuration).  

And I'm not sure I understand 

 > I have 50 simple products all using the same colour, now colour is the only option which makes the image switch there isn't a quicker way of saying for all these simple products with the colour black use the black image

You can make the color attribute use actual color boxes instead of images. Again, see [here](https://github.com/tzyganu/Switcher/wiki/configuration) the options you have for `Transformation settings`. You can select for your `color` attribute to use 'colors'. then click on the configure button below the dropdown and fill in the color hex codes or names for each color.  

Let me know if I got it right and these suggestions solve your problems.

**Comment by tzyganu** [comment]
This issue is closed due to lack of communication.
