### ISSUE TITLE
bind another page event to swatch click

### ISSUE THREAD

**Issue by albertgoplae** [tzyganu/Switcher#134]
Hi,

I want to bind another click event on a swatch click to render another part of the product page. For example, showing a different product description or product reviews. Can you kindly point me to where I should be looking? 

Thanks!

**Comment by tzyganu** [comment]
@albertgoplae  You can inject your code in the method that switches the images / media block or in the method that calls that change.  
The image is changed in the method [`changeMainImage`](https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js#L327) and the media block is changed in [`changeMediaBlock`](https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js#L350).  
Both of these are called in [`configureElement`](https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js#L374).

I will close this issue since is not related to the functionality of the extension
