### ISSUE TITLE
switching after an image has been chosen from the media block not working

### ISSUE THREAD

**Issue by jarnail104** [tzyganu/Switcher#137]
I am having this issue when I manually click on a product image from the media block below the view image. It open that image. And other thing is Zoom functionality on main image is also not working. Except this extension is doing great work.
Link: http://dev.ibywind.com/default/test-config-product.html

@tzyganu ...This is something same as this issue https://github.com/tzyganu/Switcher/issues/128 and added comment there too to get response.

**Comment by tzyganu** [comment]
@jarnail104 this extension is not a "one size fits all" extension. it's highly dependent on the theme you are using. I cannot find a solution to work with all the possible zoomers and all possible events on images. That's why I added 2 [configuration fields](https://github.com/tzyganu/Switcher/wiki/configuration) called "Js Callback after main image change" and "Js Callback after media change". You need to put here the js code that gets executed after the main image or the full media block changes.  It can be anything, like initializing the zoomer again.   
You are on your own on this. I provide the tools, but you have build a bit with them.

**Comment by jarnail104** [comment]
Dear @tzyganu  this extension working fine. Can you please give me suggestion to fix my problem: When i click on blocked image, it opened image itself. Please try to on http://dev.ibywind.com/default/test-config-product.html?___from_store=default . I dont care about zoom but can we fix it?

**Comment by jarnail104** [comment]
@tzyganu   It will be really nice of you if guide me where can i found issue like which varibale on product.js or anything. You extension is awesome but finding hard to fix this issue. Looking for your response. 

please let me if i should post my problem on http://marius-strajeru.blogspot.in/2013/10/easylife-switcher-extension.html because few users had implemented successfully and they can help me. please advice

**Comment by tzyganu** [comment]
@jarnail104 You don't have to change anything in the code. You just have to write the code that initialized your zoom function, or that handles the click on the small images in the field "Js Callback after media change". but you have to find out what the code is. I don't know how your zoom functionality works.

**Comment by jarnail104** [comment]
@tzyganu  ...forget about zoom. I just need to fix click on small image issue. How can i do that please?
