### ISSUE TITLE
Q: How to integrate with another extension...

### ISSUE THREAD

**Issue by djordje-petrovic** [tzyganu/Switcher#153]
Hi, 
As first, thanks for this great extension, it's far better than Magento native solution.
It work perfectly on product view but I want to have swatches also on Add to Cart Ajax Popup (it renders product options for configurable products) in list view. I've messed around with layout configuration trying to force render on ajax cart extension but so far no luck. Could you please give me hint where should I look? I'm starting with Magento and still don't have deep knowledge on its architecture. Where do you actually tell to EasyLife Switcher to replace original drop-down lists?

**Comment by tzyganu** [comment]
@djordje-petrovic This extension actually hooks in a javascript code that Magento already has for the configurable products page.  
And the actual change from dropdown into images or labels happens [starting here](https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js#L47).  
Follow the function names until you end up what you need

That's what I can do for now. 
I will close this issue since is not actually an issue.
