### ISSUE TITLE
version depending action in install script "data-install-2.0.0.php"

### ISSUE THREAD

**Issue by Flyingmana** [tzyganu/Switcher#90]
you have an action which depends on the version of magento.

Possible Problem: I install this module on an older Magento Version, and update Magento later. Now this code does not get executed.

(Only a guess, I did not review more to see if this is handled somewhere else too (which would be duplicated code?))

**Comment by tzyganu** [comment]
@Flyingmana 
Let me explain why.  
That install script populates some config values. 
They represent the js code executed after the main image and media blocks are changed when you select a different combination of attributes.  
in a default install of this extension, that code re-initializes the zoom functionality for the images
I had to take this approach because Magento changed the the theme and image zoomer in version 1.9.  
So version before 1.9 use the default config values and 1.9+ versions use the values from the install script.  

You are right, If you install this extension on 1.8, then upgrad to 1.9 you will have to manually change the config values.  
I had no other idea on how to handle this. I'm opened to suggestions.  

On the other hand, if you upgrade from 1.8 to 1.9, I'm sure that this will be one of the smallest issues you can have. :smile:

**Comment by Flyingmana** [comment]
We try to keep the number of possible Issues small for the update^^

this will not affect us but I think its worth to note, as others could really run into this as a problem

**Comment by tzyganu** [comment]
I will close this for now since I have no idea on how to tackle this in an other way.
