### ISSUE TITLE
When I use switch main image I can not seem to get the image to change

### ISSUE THREAD

**Issue by danhays75** [tzyganu/Switcher#92]
When I select switch main image I can not seem to get the image to change... I do have images set in each simple product.  When I select switch all media selection it does work however the photo's blow up to take up the whole screen... I think there is a JS script issue.. but I have no idea on how of were to look to fix this.  Is there a way you might point me in the right direction... I want the image to change when the color choice is selected.

**Comment by tzyganu** [comment]
@danhays75 Take a look at the [configuration](https://github.com/tzyganu/Switcher/wiki/configuration) section. There is a field called `Dom selector for main image`. This should contain the prototype (or jquery if you use that) selector for the main image. The extension uses this to determine the image that needs changing. Make sure you fill in the correct value. There is also the field `Js Callback after media change`. This should contain the javascript code to be executed after the image is changed. You can fill in here the code needed to resize the image or activate the zoom functionality. Because every theme is different from the other I cannot have a 'one code fits all' solution. That's why those fields exist. You have to fill in the values that match your theme.

**Comment by danhays75** [comment]
Would I find this information in the view.phtml section of the skin / template / default / catalog?  This is actually the information I am trying to track down from my website...I just don't know where to look.

**Comment by tzyganu** [comment]
You should find the selector for the main image by looking at the page source.  If you have something like `<img id="image" src="... "/>` then the selector is `$('image')`.

**Comment by danhays75** [comment]
the page source would be using google chrome and pulling up website and clicking view source  Would that be correct?  When I did that I could not find a "<img id=" .... I appreciate all the help your providing btw and I'm learning.

**Comment by tzyganu** [comment]
@danhays75 If your website is public post a link here and I will take a look when I have some time. 
If you are still learning, I suggest you get first familiarized with javascript and php and then Magento and after that use this extension. As stated in the description, some js dev knowledge is required to use this extension.

**Comment by danhays75** [comment]
https://www.etchedintimetreasures.com/women/test.html

Well I'm fairly familiar with all three  I just seem to be needing some help with this issue.

**Comment by tzyganu** [comment]
I think the image selector is `$$('#zoom1 img.big')[0]`. Try with that. But I have no idea how your zoomer works. I guess you're on your own with this.  
I will close this issue, since is not a real issue. It's a problem of configuration.
