### ISSUE TITLE
Show as radiobutton

### ISSUE THREAD

**Issue by Nannica** [tzyganu/Switcher#96]
Will you add the function to display attributes as radiobuttons?

**Comment by tzyganu** [comment]
@Nannica. I tried that when I started the extension, but hit a brick wall fast.  
Radio buttons are sent via POST and are stored in the `info_buyRequest` option of the cart item. I'm trying to avoid storing additional data because this can lead to inconsistent data in case the extension is disabled or the configuration is changed. You could end up with 2 products on different lines even if they represent the same product in some particular cases.  
So I dropped the idea.  
If you want to try it yourself, you can change the labels to radio buttons in the js file: https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js#L107.

I know this can be avoided if the radio buttons are used only in the UI and disabled when the product is added to cart, but I don't want to overcomplicate the extension (it's already complicated as it is).  

Sorry but I will no implement this.
